import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Clapperboard, Play } from "lucide-react";
import Link from "next/link";
import { GenreType } from "@/types/global";

async function fetchGenre(): Promise<GenreType[]> {
    try {
        const res = await fetch(
            "https://api.themoviedb.org/3/genre/movie/list",
            {
                headers: {
                    Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
                },
                next: { revalidate: 60 * 60 }, // Next.js 推奨: キャッシュ制御　- 1時間
            }
        );

        if (!res.ok) {
            throw new Error(`Http error: ${res.status}`);
        }
        const data = await res.json();

        if (!Array.isArray(data.genres)) {
            throw new Error("Invalid response format.");
        }

        return data.genres;
    } catch (error) {
        console.error("fetchGenre failed: ", error);
        return [];
    }
}

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const genreList = await fetchGenre();
    const hasError = genreList.length === 0;
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="p-4 border-b flex items-center justify-between">
                    <Link href={`/`}>
                        <h1 className="font-bold text-2xl items-center flex gap-2 justify-between">
                            <Clapperboard />
                            Next Movie
                        </h1>
                    </Link>
                    <form className="flex items-center gap-1">
                        <Input placeholder="Search" />
                        <Button>Search</Button>
                    </form>
                </header>
                <section className="flex">
                    <aside className="p-4 border-r w-60 flex flex-col gap-1">
                        {hasError && (
                            <p className="text-sm text-red-500">
                                Failed to fetch Genre List.
                            </p>
                        )}
                        {!hasError &&
                            genreList.map((genre) => {
                                return (
                                    <Button
                                        key={genre.id}
                                        variant="outline"
                                        className="flex items-center justify-start"
                                    >
                                        <Link
                                            href={`/genre/${genre.name}/${genre.id}`}
                                            className="flex gap-2 items-center justify-start"
                                        >
                                            <Play />
                                            {genre.name}
                                        </Link>
                                    </Button>
                                );
                            })}
                    </aside>
                    <main className="flex-1 flex justify-center">
                        <div className="w-full max-w-5xl p-3">{children}</div>
                    </main>
                </section>
            </body>
        </html>
    );
}
