import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Clapperboard, Play } from "lucide-react";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { GenreType } from "@/.next/types/global";
import { redirect } from "next/navigation";

async function fetchGenres(): Promise<GenreType[]> {
    const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
        headers: {
            Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
        },
    });

    const data = await res.json();
    return data.genres;
}

async function search(formData: FormData) {
    "use server";

    const q = formData.get("q");
    redirect(`/search?q=${q}`);
}

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const genres = await fetchGenres();
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="p-4 border-b flex items-center justify-between">
                    <h1 className="font-bold text-2xl flex gap-2 items-center">
                        <Clapperboard />
                        Next Movie
                    </h1>

                    <form action={search} className="flex items-center gap-1">
                        <Input name="q" placeholder="Search" />
                        <Button>Search</Button>
                    </form>
                </header>
                <section className="flex">
                    <aside className="p-4 border-r w-60 flex flex-col gap-1">
                        {genres.map((genre) => {
                            return (
                                <Button
                                    key={genre.id}
                                    asChild
                                    variant="outline"
                                    className="flex items-center justify-start"
                                >
                                    <Link
                                        href={`/genre/${genre.name}/${genre.id}`}
                                        className="flex gap-2 items-center justify-start"
                                    >
                                        <Play />
                                        {genre.name}
                                    </Link>
                                </Button>
                            );
                        })}
                    </aside>
                    <main>{children}</main>
                </section>
            </body>
        </html>
    );
}
